org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# 16KB page size support (Google Play requirement - Nov 2025)
android.experimental.testOptions.managedDevices.setupTimeoutMinutes=180
android.defaults.buildfeatures.buildconfig=true
